on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: tag
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> $GITHUB_OUTPUT

  publish-oci:
    runs-on: ubuntu-latest
    name: Publish Module as OCI
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true'}}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish-oci
        with:
          repository: ${{ github.repository }}
          tag: ${{ needs.release-please.outputs.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
